### ISSUE TITLE
Theme and plugins

### ISSUE THREAD

**Issue by gudstrand** [kaelri/obsidian-dataview-test-vault#1]
Which theme are you using for this vault?  Any plugins I shouls install and enable?

**Comment by kaelri** [comment]
The theme in the readme screenshot is [Minimal](https://github.com/kepano/obsidian-minimal), though it would probably look decent in any dark-mode theme. The only plugin is [Dataview](https://blacksmithgu.github.io/obsidian-dataview/) with “Enable JavaScript Queries” enabled.

**Comment by gudstrand** [comment]
Thank you!
