### ISSUE TITLE
Any resources on how to customize this?

### ISSUE THREAD

**Issue by blackpeasy** [kaelri/obsidian-dataview-test-vault#2]
I love this design, but I'm having a hard time customizing it to my needs, as I am only used to messing with standard dataview tables. Have you planned any guides for how to customize this?

An example: Inside each of my project notes I have an overview of subtasks. Each task has it's own note where I actually write out the contents of that task (meeting notes, synopsis etc.)

The list looks like this:
![image](https://user-images.githubusercontent.com/92858268/147131681-25ab489f-ac73-44bf-b778-b9f478958fcd.png)

Would it be possible to populate your 'notes' section of the project-card with these subtasks and their YAML Metadata?

**Comment by kaelri** [comment]
This is really just a copy of the views I created for my personal vault. However, I could provide some expanded guidance if there’s enough interest.

It’s built on top of the same basic Dataview features that you’re using, so making this work for your setup would be a matter of 1) passing your Dataview query parameters into the `dv.view()` function, and 2) accessing the YAML metadata properties within that function. For example, if your sub-tasks have a metadata property called `intensity` (per your screenshot), you can get the value of that as a JavaScript variable, and then use that to write the HTML that displays in your note:

```js
…
for (let i = 0; i < projects.length; i++) {
    const project = projects[i];

    html += `<td>${project.intensity}</td>`;

}
…
```

It takes some more manual work than the built-in Dataview templates, and it’s best if you have some familiarity with writing HTML and JavaScript code. With that, you can expand it to make use of any other YAML properties.

**Comment by blackpeasy** [comment]
Thanks! Will try to have a crack at it even though HTML + JS might be too much for me.
